import React, { useEffect, useState } from "react";

const BRAND = {
  magenta: "#C11D63", magentaDark: "#9F1D55", blush: "#FDF2F7",
  blushStrong: "#F7E2EB", dark: "#121826", text: "#121826",
  muted: "#5C667A", line: "#E3E7EE", soft: "#F6F8FB", eyebrowDark: "#F2A7C6",
};

const canonicalUrl = "https://www.stepes.com/resources/translation-guides/prior-art-translation-patentability-fto-invalidity/";
const sectionUrl = (id) => `${canonicalUrl}#${id}`;
const links = {
  resources: "https://www.stepes.com/resources/",
  translationGuides: "https://www.stepes.com/resources/translation-guides/",
  patentServices: "https://www.stepes.com/patent-translation-services/",
  claimsChecklist: "https://www.stepes.com/resources/translation-guides/patent-claims-translation-quality-checklist/",
  aiPatentGuide: "https://www.stepes.com/resources/ai-translation-insights/ai-patent-translation-research-vs-filing-grade/",
  pctGuide: "https://www.stepes.com/resources/translation-guides/pct-patent-translation-national-phase-guide/",
  chemicalPatent: "https://www.stepes.com/chemical-patent-translation-services/",
  terminology: "https://www.stepes.com/terminology-management/",
  certified: "https://www.stepes.com/certified-translation-services/",
  contact: "https://www.stepes.com/contact-us/",
  quote: "https://app.stepes.com/quote/",
};

const breadcrumbs = [
  { label: "Resources", href: links.resources },
  { label: "Translation Guides", href: links.translationGuides },
  { label: "Prior Art Translation for Patentability, FTO, and Invalidity", current: true },
];

const tocItems = [
  ["research-objectives","Research Objectives"],
  ["translation-depth","Translation Scope"],
  ["translation-levels","Translation Levels"],
  ["patentability","Patentability"],
  ["fto","Freedom to Operate"],
  ["invalidity","Invalidity"],
  ["prior-art-sources","Prior-Art Sources"],
  ["document-parts","What to Translate"],
  ["progressive-workflow","Progressive Workflow"],
  ["ai-screening","AI & Human Review"],
  ["traceability","Quality & Traceability"],
  ["formal-use","Formal Use & Security"],
  ["planning-checklist","Planning Checklist"],
  ["faqs","FAQs"],
  ["official-sources","Official Sources"],
].map(([id,label])=>({id,label}));

const takeaways = [
  ["Start With the Research Question","Patentability, freedom to operate, invalidity, technology landscaping, competitive research, and due diligence ask different questions. Translation scope should follow the purpose of the research."],
  ["Screen Broadly Before Translating Deeply","Large research sets can often be triaged before resources are committed to complete professional translation."],
  ["Translate the Content That Drives the Analysis","Claims, technical disclosures, examples, specifications, tables, figures, and non-patent literature can matter differently depending on the assignment."],
  ["Increase Human Review as the Stakes Rise","AI-assisted translation can accelerate comprehension, while decision-critical references benefit from professional translation and appropriate independent review."],
  ["Preserve Traceability to the Original Source","Claim numbers, paragraphs, figures, tables, patent identifiers, citations, and other source references should remain easy to correlate with the original document."],
].map(([title,text])=>({title,text}));

const levels = [
  ["01","Document Screening","Rapid AI-assisted and/or linguist-supported comprehension to determine whether a foreign-language document appears potentially relevant enough for further review.","Large search-result sets, technology landscaping, competitor monitoring, portfolio review, and early-stage research."],
  ["02","Summary Translation","A focused explanation of the invention, technical disclosure, claims, findings, or other requested content without translating every source sentence.","Projects that need more context than an abstract provides but do not yet require a complete translation."],
  ["03","Selected-Passage Translation","Professional translation of specifically identified claims, embodiments, paragraphs, examples, tables, figures, definitions, citations, or other requested passages.","Attorney- or researcher-directed analysis of the portions most relevant to the next research decision."],
  ["04","Full Professional Translation","Complete human translation when reviewers need full technical and linguistic context across claims, descriptions, examples, drawings, terminology, numbers, units, and cross-references.","High-priority patentability, FTO, invalidity, due-diligence, licensing, expert-review, or other decision-critical references."],
  ["05","Verified or Certified Translation","Additional independent review, certification, declaration, bilingual presentation, or other documented verification when requested for a formal or evidentiary use.","Matter-specific requirements identified by counsel, a court, patent office, administrative body, or other receiving party."],
].map(([number,title,text,uses])=>({number,title,text,uses}));

const decisionRows = [
  ["Patentability","Screening or summary","Technical disclosure, embodiments, relevant claims, examples","Reference appears materially relevant","Selected passages or full professional translation"],
  ["Freedom to Operate","Screening and claim review","Claims, relevant specification, family context","Claim language may be consequential to counsel’s analysis","Human-reviewed claims or full relevant patent"],
  ["Invalidity","Screening or selected passages","Potentially relevant disclosure and supporting context","Reference becomes decision-critical","Complete, independently reviewed, or formally documented translation"],
  ["Technology Landscape","AI-assisted screening","Abstracts, technical concepts, classifications, summaries","Particular technologies or competitors become strategic","Selected professional translation"],
  ["Portfolio Due Diligence","Prioritized review or summaries","Claims, technologies, families, selected supporting documents","Asset or risk affects the transaction","Full professional translation"],
  ["Competitive Research","Screening and summaries","Technologies, applications, products, inventors, assignees","A document warrants deeper investigation","Selected or full translation"],
].map(([objective,start,prioritize,escalate,final])=>({objective,start,prioritize,escalate,final}));

const qualityRows = [
  ["Technical meaning","Disclosure, processes, components, relationships, results, and scientific concepts are accurately conveyed."],
  ["Claims","Dependencies, limitations, numbering, terminology, antecedent references, ranges, and alternatives are preserved."],
  ["Numbers and units","Values, percentages, ranges, dimensions, temperatures, concentrations, equations, formulas, and units are checked."],
  ["Names and references","Patent numbers, publication numbers, inventor names, entities, cited documents, and other identifiers remain accurate."],
  ["Figures and tables","Translated labels, references, tables, and surrounding text remain properly aligned."],
  ["Terminology","Important technical language remains consistent within the document and, where appropriate, across related references."],
  ["Translation scope","The deliverable clearly identifies whether it is a summary, selected-passage translation, claim translation, or complete translation."],
  ["Source traceability","Reviewers can quickly locate translated information in the original source."],
  ["Review level","Professional or independent review matches the intended use of the translation."],
].map(([area,check])=>({area,check}));

const expertise = [
  ["Biotechnology and Pharmaceuticals","Molecular biology, genetics, biologics, diagnostics, therapeutic technologies, formulations, analytical methods, laboratory processes, sequences, and drug-development terminology."],
  ["Chemistry and Materials Science","Organic and inorganic chemistry, polymers, compounds, coatings, formulations, reaction processes, catalysts, analytical methods, and advanced materials.",links.chemicalPatent,"Explore Chemical Patent Translation Services"],
  ["Medical Devices and Diagnostics","Diagnostic systems, surgical devices, imaging, monitoring technologies, in vitro diagnostics, connected medical technologies, and combination products."],
  ["Electronics and Semiconductors","Semiconductor fabrication, integrated circuits, sensors, electronics, materials, chip architectures, packaging, lithography, process equipment, and electronic systems."],
  ["Software, AI, and Telecommunications","Algorithms, machine learning, computing architectures, data processing, communications protocols, networking, wireless technologies, interfaces, and software-implemented inventions."],
  ["Mechanical and Industrial Engineering","Machinery, manufacturing systems, robotics, automation, automotive technologies, energy systems, industrial processes, structures, components, and control systems."],
].map(([title,text,href,linkLabel])=>({title,text,href,linkLabel}));

const checklistGroups = [
  ["Define the Research Objective",["Patentability","Freedom to operate","Invalidity or validity research","Litigation","Technology landscaping","Competitive intelligence","Portfolio review, licensing, or due diligence"]],
  ["Identify the Documents",["Patent or publication number","Patent-family information","Source URL or database record","Researcher notes or search-report citations","Related documents"]],
  ["Define Translation Depth",["Screening","Summary","Claims only","Selected passages","Complete translation","Independent review or certification"]],
  ["Prioritize the References",["Identify which documents require attention first","Use staged delivery when research priorities may change during translation"]],
  ["Mark Relevant Passages",["Claim numbers","Paragraph numbers","Page ranges","Figures and tables","Other source identifiers"]],
  ["Identify the Technical Field",["Describe the technology clearly enough to assign qualified translators and reviewers"]],
  ["Supply Reference Material",["Related patents and family translations","Glossaries and product documentation","Technical standards or scientific references","Earlier approved translations or attorney-approved terminology"]],
  ["Define Traceability Requirements",["Paragraph and claim numbering","Page references","Figures and tables","Source/target side-by-side layout"]],
  ["Define the Review Level",["Research comprehension","Professional translation","Independent review","Certification or another documented quality step"]],
  ["Confirm Delivery Requirements",["Deadline and priority order","File format","Bilingual or monolingual output","Staged delivery and naming conventions","Matter-specific instructions"]],
  ["Identify Security Requirements",["Confidentiality requirements","Access controls","Data-handling instructions","AI-use restrictions where applicable"]],
].map(([title,items])=>({title,items}));

const faqs = [
  ["What is prior art translation?","Prior art translation provides target-language access to foreign-language patents, technical publications, scientific literature, and other materials selected for patent research. Depending on the purpose, the work may range from rapid document screening and summaries to selected-passage translation, complete professional translation, or independently verified translation."],
  ["Do I need to translate every foreign-language patent found in a prior-art search?","Usually not. Large search result sets can often be screened first using abstracts, AI-assisted translation, bibliographic information, summaries, or targeted linguistic review. Documents that appear more important can then be escalated to selected-passage or complete professional translation. The appropriate workflow depends on the research instructions and should be determined by the patent professionals directing the project."],
  ["Can AI translate prior art for patent research?","AI-assisted translation can be highly useful for document screening, initial comprehension, terminology extraction, large-volume triage, and identifying material for deeper review. Higher-risk or decision-critical content should receive the level of qualified human translation and review appropriate to its intended use. AI should support the research process, not independently determine patentability, infringement, FTO, validity, or the legal significance of a reference."],
  ["Is an abstract enough for patentability research?","An abstract can be extremely useful for initial screening, but it does not contain every detail of the complete patent document. If a reference appears potentially important, researchers may request translation of relevant claims, specification passages, examples, embodiments, figures, or the complete document."],
  ["Should FTO translation focus on patent claims?","Claims are particularly important in FTO analysis because patent rights are defined by claims, and FTO research is jurisdiction- and legal-status-specific. Patent professionals may also request relevant portions of the specification, definitions, figures, prosecution materials, or patent-family documents for additional context. Stepes translates the material identified for review; qualified patent professionals determine claim scope and FTO conclusions."],
  ["What is the difference between prior-art translation for patentability and FTO?","Patentability research generally considers earlier disclosures that may be relevant to whether an invention satisfies applicable patentability requirements. FTO research considers potentially applicable patent rights that may affect a product, process, or commercial activity in a particular jurisdiction. The same patent may be relevant to both questions, but the research purpose and translation priorities can differ significantly."],
  ["Can Stepes translate only selected patent claims or passages?","Yes. Prior-art projects can include individual claims, groups of claims, specific numbered paragraphs, embodiments, examples, tables, figures, or other selected portions. Clearly defined source identifiers help maintain traceability and make the limits of the translated scope clear."],
  ["When should a complete foreign patent be professionally translated?","Full professional translation may be appropriate when a reference becomes sufficiently important that researchers, attorneys, engineers, or experts need complete access to its technical context. Examples can include decision-critical patentability references, important FTO patents, high-priority invalidity material, litigation documents, licensing reviews, and due-diligence matters."],
  ["Does prior-art translation need to be certified?","Not routinely. Screening, internal research, and early-stage analysis generally do not automatically require certified translation. Certification or other formal documentation may become appropriate when requested for a particular court, patent office, administrative proceeding, expert process, or other formal use. The receiving authority and counsel should determine the applicable requirement."],
  ["Can Stepes translate scientific papers and other non-patent literature?","Yes. Prior-art and patent research may involve scientific papers, journals, conference proceedings, standards, technical manuals, theses, product materials, and other foreign-language technical content in addition to patents. Translation scope can range from summaries or selected passages to complete professional translation."],
  ["Does Stepes determine whether a reference qualifies as prior art or invalidates a patent?","No. Stepes provides translation, technical-language, formatting, and multilingual workflow support. We do not render legal opinions regarding prior-art status, patentability, validity, invalidity, infringement, claim construction, freedom to operate, critical dates, or evidentiary significance. Those determinations remain with the client and its qualified patent counsel or other patent professionals."],
].map(([q,a])=>({q,a}));

const sources = [
  ["WIPO PATENTSCOPE","World Intellectual Property Organization","Search published PCT applications and participating national and regional patent collections.","https://patentscope.wipo.int/search/en/search.jsf"],
  ["WIPO Patent Information","World Intellectual Property Organization","Guidance on patent information for research, technical intelligence, patentability assessment, and related innovation activities.","https://www.wipo.int/en/web/patents/patent-information"],
  ["EPO Guidelines for Examination","European Patent Office","Official examination guidance covering prior art, novelty, inventive step, and non-official-language documents.","https://www.epo.org/en/legal/guidelines-epc/2026/g_iv_4.html"],
  ["USPTO Patent Public Search","United States Patent and Trademark Office","Public access to U.S. patents and published patent applications through the USPTO search environment.","https://www.uspto.gov/patents/search/patent-public-search/"],
  ["USPTO MPEP § 2128","United States Patent and Trademark Office","Official examination guidance concerning printed publications and public accessibility.","https://www.uspto.gov/web/offices/pac/mpep/s2128.html"],
  ["Inter Partes Review","USPTO Patent Trial and Appeal Board","Official information about inter partes review and proceeding-specific requirements.","https://www.uspto.gov/patents/ptab/trials/inter-partes-review"],
].map(([title,organization,text,href])=>({title,organization,text,href}));

const related = [
  ["Patent Translation Services","Professional patent translation for international filing, prosecution, prior-art research, patent litigation, portfolio management, and multilingual IP programs.",links.patentServices],
  ["Patent Claims Translation Quality Checklist","Review claim dependencies, terminology, antecedent references, numbers, units, drawings, completeness, and other quality controls.",links.claimsChecklist],
  ["AI Patent Translation: Research Use vs. Filing-Grade Translation","Understand where AI can accelerate patent research and where professional translation and human quality control become increasingly important.",links.aiPatentGuide],
  ["PCT Patent Translation and National Phase Guide","Plan translation for PCT applications, national and regional phase entry, claims, amendments, priority materials, and coordinated multilingual patent families.",links.pctGuide],
].map(([title,text,href])=>({title,text,href}));

function Icon({ name, size = 20 }) {
  const p = {width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.7,strokeLinecap:"round",strokeLinejoin:"round","aria-hidden":true};
  if(name==="arrow") return <svg {...p}><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></svg>;
  if(name==="search") return <svg {...p}><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.2 4.2"/></svg>;
  if(name==="target") return <svg {...p}><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/></svg>;
  if(name==="layers") return <svg {...p}><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></svg>;
  return <svg {...p}><path d="m5 12 4 4L19 6"/></svg>;
}

function ExternalLink({href,children}) { return <a className="text-link" href={href} target="_blank" rel="noreferrer"><span>{children}</span><Icon name="arrow" size={16}/></a>; }

export default function StepesPriorArtTranslationGuide(){
  const [activeId,setActiveId]=useState("research-objectives");
  const [openFaq,setOpenFaq]=useState(null);
  useEffect(()=>{
    if(typeof window==="undefined" || !("IntersectionObserver" in window)) return;
    const nodes=tocItems.map(x=>document.getElementById(x.id)).filter(Boolean);
    const io=new IntersectionObserver(entries=>{
      const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);
      if(visible[0]?.target?.id) setActiveId(visible[0].target.id);
    },{rootMargin:"-18% 0px -68% 0px",threshold:[0,.1,.3]});
    nodes.forEach(n=>io.observe(n)); return ()=>io.disconnect();
  },[]);
  const jump=(e,id)=>{ const n=typeof document!=="undefined"?document.getElementById(id):null; if(!n)return; e.preventDefault(); n.scrollIntoView({behavior:"smooth",block:"start"}); if(typeof window!=="undefined") window.history?.replaceState?.(null,"",`#${id}`); };

  return <main className="pa-guide">
    <style>{`
      :root{--m:${BRAND.magenta};--md:${BRAND.magentaDark};--bl:${BRAND.blush};--bl2:${BRAND.blushStrong};--dk:${BRAND.dark};--tx:${BRAND.text};--mu:${BRAND.muted};--ln:${BRAND.line};--sf:${BRAND.soft};--ed:${BRAND.eyebrowDark}}
      *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0}.pa-guide{overflow-x:clip;background:#fff;color:var(--tx);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:18px;line-height:1.68}.pa-guide a{color:var(--m);text-decoration:none}.pa-guide a:focus-visible,.pa-guide button:focus-visible,.pa-guide summary:focus-visible{outline:3px solid rgba(193,29,99,.24);outline-offset:4px}.shell{width:100%;max-width:1280px;margin:0 auto;padding:0 56px}.reading{max-width:760px}.section{padding:96px 0}.pa-guide h1,.pa-guide h2,.pa-guide h3{margin:0;color:var(--tx);font-family:"Inter Tight",Inter,ui-sans-serif,system-ui,sans-serif;font-weight:500;overflow-wrap:anywhere}.pa-guide h1{max-width:730px;font-size:48px;line-height:1.3;letter-spacing:-.5px}.pa-guide h2{font-size:36px;line-height:1.3;margin-bottom:22px}.pa-guide h3{font-size:24px;line-height:1.35;margin-bottom:12px}.pa-guide p{margin:0 0 22px;color:var(--mu);overflow-wrap:anywhere}.pa-guide li{color:var(--mu);overflow-wrap:anywhere}.lead{max-width:810px;font-size:20px;line-height:1.65}.eyebrow{margin:0 0 16px!important;color:var(--m)!important;font-size:11px!important;line-height:1.3!important;font-weight:600!important;letter-spacing:.16em!important;text-transform:uppercase}.dark .eyebrow{color:var(--ed)!important}.text-link{display:inline-flex;align-items:center;gap:8px;max-width:100%;min-width:0;color:var(--m)!important;font-size:16px;font-weight:600;line-height:1.45;white-space:normal;overflow-wrap:anywhere}.text-link:hover{color:var(--md)!important}.text-link svg{flex:0 0 auto}.button-row{display:flex;flex-wrap:wrap;align-items:center;gap:12px;margin-top:30px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;min-width:0;min-height:50px;padding:12px 22px;border:1px solid transparent;border-radius:999px;font-size:16px;line-height:1.25;font-weight:600;text-align:center;white-space:normal;overflow-wrap:anywhere;transition:.2s ease}.btn-primary,.btn-primary:link,.btn-primary:visited,.btn-primary:hover,.btn-primary:active,.btn-primary:focus,.btn-primary:focus-visible{background:var(--m);color:#fff!important}.btn-primary *,.btn-primary svg,.btn-primary svg *{color:#fff!important;stroke:#fff!important;fill:none}.btn-primary:hover{background:var(--md);transform:translateY(-1px);box-shadow:0 12px 28px rgba(159,29,85,.16)}.btn-secondary{color:var(--tx)!important;background:#fff;border-color:var(--ln)}.btn-secondary:hover{border-color:#C9CFD9;transform:translateY(-1px)}
      .breadcrumb-wrap{padding-top:28px;background:#fff}.breadcrumb ol{display:flex;flex-wrap:wrap;align-items:baseline;gap:7px 9px;margin:0;padding:0;list-style:none}.breadcrumb li{display:inline-flex;align-items:baseline;max-width:100%;min-width:0;color:#6B7485;font-size:14px;line-height:1.45}.breadcrumb li:not(:last-child):after{content:"/";flex:0 0 auto;margin-left:9px;color:#A6ADBA;font-weight:400}.breadcrumb a{color:#6B7485}.breadcrumb a:hover{color:var(--m)}.breadcrumb .current{max-width:100%;color:#3D4657;font-weight:500;overflow-wrap:anywhere}
      .hero{padding:50px 0 82px;background:radial-gradient(circle at 88% 18%,rgba(193,29,99,.055),transparent 31%),#fff}.hero-grid{display:block;max-width:1000px}.hero-copy{max-width:960px;min-width:0}.hero-copy h1{max-width:920px}.hero-copy .lead{max-width:840px;margin-top:24px;margin-bottom:0;color:#4F5A6C}.hero-route{display:flex;align-items:center;flex-wrap:wrap;gap:10px 12px;max-width:900px;margin-top:28px;padding-top:22px;border-top:1px solid var(--ln)}.hero-route .route-label{color:#7A8494;font-size:13px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.hero-route .route-step{display:inline-flex;align-items:center;min-height:34px;padding:6px 10px;border:1px solid #DCE1E8;border-radius:999px;background:#fff;color:#475264;font-size:14px;font-weight:600;line-height:1.35}.hero-route .route-arrow{color:#9AA3B1;font-size:15px;line-height:1}
      .takeaways{padding:78px 0;background:var(--bl);border-top:1px solid #F3DCE7;border-bottom:1px solid #F3DCE7}.takeaway-grid{display:grid;grid-template-columns:minmax(260px,.72fr) minmax(0,1.28fr);gap:70px;align-items:start}.takeaway-intro{position:sticky;top:108px}.takeaway-intro p{max-width:440px;font-size:18px}.takeaway-list{border-top:1px solid #E6C9D7}.takeaway-row{display:grid;grid-template-columns:38px minmax(0,1fr);gap:18px;padding:24px 0;border-bottom:1px solid #E6C9D7}.takeaway-mark{display:grid;place-items:center;width:30px;height:30px;margin-top:2px;border:1px solid rgba(193,29,99,.28);border-radius:50%;color:var(--m)}.takeaway-row strong{display:block;margin-bottom:6px;color:var(--tx);font-family:"Inter Tight",Inter,sans-serif;font-size:19px;font-weight:600;line-height:1.35}.takeaway-row p{margin:0;font-size:16px;line-height:1.62}
      .article-region{padding:92px 0 40px}.article-layout{display:grid;grid-template-columns:240px minmax(0,880px);gap:48px;width:100%;max-width:1168px;margin:0 auto}.desktop-toc{align-self:start;position:sticky;top:96px;max-height:calc(100vh - 120px);overflow:auto;padding:0 6px 10px 0}.toc-title{margin:0 0 16px;color:#5F6979;font-size:14px;font-weight:600;text-transform:uppercase;letter-spacing:.08em}.toc-list{margin:0;padding:0;list-style:none;border-left:1px solid #D9DEE6}.toc-link{display:block;margin-left:-1px;padding:9px 0 9px 16px;border-left:2px solid transparent;color:#657083!important;font-size:15px;line-height:1.4;font-weight:500}.toc-link:hover{color:var(--m)!important}.toc-link.active{border-left-color:var(--m);color:var(--m)!important;font-weight:600}.mobile-toc{display:none;margin-bottom:42px;border:1px solid var(--ln);border-radius:18px;background:#fff;overflow:hidden}.mobile-toc summary{position:relative;cursor:pointer;list-style:none;padding:16px 48px 16px 18px;color:var(--tx);font-size:16px;font-weight:600}.mobile-toc summary::-webkit-details-marker{display:none}.mobile-toc summary:after{content:"+";position:absolute;right:18px;top:13px;color:var(--m);font-size:24px;line-height:1}.mobile-toc[open] summary:after{content:"–"}.mobile-toc .toc-list{margin:0 18px 16px}.mobile-toc .toc-link{display:flex;align-items:center;min-height:44px;font-size:16px}.article-main{min-width:0}.guide-section{max-width:880px;padding:0 0 84px;scroll-margin-top:112px}.guide-section+.guide-section{padding-top:6px}.chapter-intro{max-width:800px;margin-bottom:34px!important;font-size:19px;line-height:1.68}.subsection{max-width:760px;padding-top:28px}.subsection+.subsection{margin-top:14px;border-top:1px solid var(--ln)}.important-note{max-width:760px;margin:30px 0 0;padding:24px 26px;border:1px solid #E9D5DF;border-radius:18px;background:var(--bl)}.important-note strong{display:block;margin-bottom:7px;color:var(--tx);font-size:16px;font-weight:600}.important-note p{margin:0;font-size:16px;line-height:1.62}.legal-boundary{max-width:760px;margin-top:30px;padding:20px 0;border-top:1px solid var(--ln);border-bottom:1px solid var(--ln)}.legal-boundary strong{display:block;margin-bottom:7px;color:var(--tx);font-size:16px;font-weight:600}.legal-boundary p{margin:0;font-size:16px;line-height:1.62}.source-note{display:flex;align-items:flex-start;gap:10px;max-width:760px;margin-top:24px;padding-top:18px;border-top:1px solid var(--ln);color:#687386;font-size:15px;line-height:1.55}.source-note strong{flex:0 0 auto;color:#4A5567;font-weight:600}.source-note a{font-weight:600}
      .three-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0 26px;margin-top:36px;border-top:1px solid var(--ln)}.question{padding:28px 0 24px;border-bottom:1px solid var(--ln)}.question h3{display:flex;align-items:center;gap:10px;font-size:22px}.question h3 span{display:grid;place-items:center;flex:0 0 auto;width:28px;height:28px;border:1px solid rgba(193,29,99,.28);border-radius:50%;color:var(--m);font-family:Inter,sans-serif;font-size:13px;font-weight:700}.question p{margin-bottom:0;font-size:16px;line-height:1.62}.scenario{display:grid;grid-template-columns:170px minmax(0,1fr);gap:28px;margin-top:34px;padding:28px;border:1px solid var(--ln);border-radius:22px;background:#fff}.scenario-label{color:var(--m);font-size:13px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.scenario p{margin-bottom:14px;font-size:16px}.scope-flow{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}.scope-flow span,.term-chips span{display:inline-flex;align-items:center;min-height:36px;padding:7px 11px;border:1px solid #DCE1E8;border-radius:999px;background:#FAFBFC;color:#475264;font-size:14px;font-weight:600}
      .levels{margin-top:34px;border-top:1px solid var(--ln)}.level{display:grid;grid-template-columns:74px 220px minmax(0,1fr);gap:24px;padding:28px 0;border-bottom:1px solid var(--ln)}.level-number{color:var(--m);font-family:"Inter Tight",Inter,sans-serif;font-size:28px;font-weight:500;line-height:1}.level h3{margin:0;font-size:20px}.level-copy p{margin-bottom:10px;font-size:16px;line-height:1.62}.level-use{display:block;color:#667184;font-size:16px;line-height:1.55}.matrix-heading{margin:30px 0 26px}.matrix-heading p{max-width:790px;margin-bottom:0;font-size:17px}.table-wrap{width:100%;overflow:hidden;border:1px solid var(--ln);border-radius:20px;background:#fff}.responsive-table{width:100%;border-collapse:collapse;table-layout:fixed}.responsive-table th,.responsive-table td{padding:16px 15px;text-align:left;vertical-align:top;border-bottom:1px solid var(--ln);overflow-wrap:anywhere}.responsive-table th{background:#F7F8FA;color:#303A4C;font-size:16px;font-weight:600;line-height:1.45}.responsive-table td{color:#5A6577;font-size:16px;line-height:1.52}.responsive-table td:first-child{color:var(--tx);font-weight:600}.responsive-table tr:last-child td{border-bottom:0}.matrix-note{margin-top:16px!important;color:#6B7585!important;font-size:15px!important;line-height:1.55!important}.mid-cta{display:flex;align-items:center;justify-content:space-between;gap:26px;margin-top:34px;padding:24px 26px;border-top:1px solid var(--ln);border-bottom:1px solid var(--ln)}.mid-cta strong{display:block;max-width:520px;color:var(--tx);font-family:"Inter Tight",Inter,sans-serif;font-size:19px;font-weight:600;line-height:1.4}
      .source-grid,.ai-grid,.trace-grid,.expertise-grid,.checklist-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 34px;margin-top:34px;border-top:1px solid var(--ln)}.source-group,.ai-col,.trace-item,.expertise-item,.check-group{padding:26px 0;border-bottom:1px solid var(--ln)}.source-group h3,.ai-col h3,.expertise-item h3,.check-group h3{font-size:20px}.source-group ul,.ai-col ul,.check-group ul{margin:0;padding:0;list-style:none}.source-group li{padding:9px 0;border-bottom:1px solid #EFF1F4;font-size:16px;line-height:1.5}.part-list{margin-top:34px;border-top:1px solid var(--ln)}.part{display:grid;grid-template-columns:220px minmax(0,1fr);gap:34px;padding:26px 0;border-bottom:1px solid var(--ln)}.part h3{margin:0;font-size:20px}.part p{margin:0;font-size:16px;line-height:1.62}
      .dark-framework{margin-top:18px;padding:42px;border-radius:28px;background:var(--dk);color:#fff}.dark-framework h2{color:#fff}.dark-framework .framework-intro{max-width:760px;color:#C9D0DD;font-size:18px}.funnel{display:grid;gap:12px;margin-top:36px}.stage{display:grid;grid-template-columns:230px minmax(0,1fr);gap:22px;min-height:76px;margin:0 auto;padding:16px 20px;border:1px solid rgba(255,255,255,.14);border-radius:16px;background:rgba(255,255,255,.06)}.stage strong{color:#fff;font-size:16px;line-height:1.45}.stage span{color:#CBD2DE;font-size:15px;line-height:1.5}.stage:last-child{border-color:rgba(242,167,198,.4);background:rgba(193,29,99,.2)}.framework-note{margin:24px 0 0!important;color:#BFC7D4!important;font-size:14px!important;line-height:1.55!important}
      .ai-col h3{display:flex;align-items:center;gap:10px}.ai-col h3 svg{color:var(--m)}.ai-col ul{display:grid;gap:9px;margin-top:16px}.ai-col li{position:relative;padding-left:20px;font-size:16px;line-height:1.55}.ai-col li:before{content:"";position:absolute;left:0;top:.65em;width:6px;height:6px;border:1px solid var(--m);border-radius:50%}.risk-route{display:flex;align-items:stretch;margin-top:28px;border:1px solid var(--ln);border-radius:18px;overflow:hidden}.risk-route div{flex:1;padding:18px;background:#fff;border-right:1px solid var(--ln)}.risk-route div:last-child{border-right:0;background:var(--bl)}.risk-route strong{display:block;margin-bottom:5px;color:var(--tx);font-size:16px}.risk-route span{display:block;color:#667184;font-size:16px;line-height:1.5}.trace-item strong{display:block;margin-bottom:8px;color:var(--tx);font-size:18px;font-weight:600}.trace-item p,.expertise-item p{margin:0;font-size:16px;line-height:1.6}.expertise-item p{margin-bottom:12px}.term-chips{display:flex;flex-wrap:wrap;gap:9px;margin-top:24px}.formal-list,.security-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 28px;margin:24px 0 0;padding:0;list-style:none}.formal-list li,.security-list li{position:relative;padding:12px 0 12px 22px;border-bottom:1px solid var(--ln);font-size:16px;line-height:1.5}.formal-list li:before,.security-list li:before{content:"";position:absolute;left:0;top:1.15em;width:7px;height:7px;border-radius:2px;background:var(--m)}
      .checklist-panel{margin-top:34px;padding:34px;border:1px solid var(--ln);border-radius:26px;background:#fff}.checklist-grid{margin-top:0;border-top:0;gap:0 38px}.check-group{padding:24px 0}.check-group ul{display:grid;gap:9px}.check-group li{display:grid;grid-template-columns:20px minmax(0,1fr);gap:10px;align-items:start;font-size:16px;line-height:1.52}.checkmark{width:16px;height:16px;margin-top:4px;border:1.5px solid #B3BCC9;border-radius:4px;background:#fff}
      .faq-wrap{max-width:880px;border:1px solid var(--ln);border-radius:22px;background:#fff;overflow:hidden}.faq-item{border-top:1px solid var(--ln)}.faq-item:first-child{border-top:0}.faq-question{display:flex;width:100%;min-height:66px;align-items:center;justify-content:space-between;gap:22px;padding:18px 22px;border:0;background:#fff;color:var(--tx);cursor:pointer;text-align:left;font:inherit;font-size:17px;font-weight:600;line-height:1.45}.faq-symbol{display:grid;place-items:center;flex:0 0 auto;width:30px;height:30px;border:1px solid #DDE2E9;border-radius:50%;color:var(--m);font-size:21px}.faq-answer{padding:0 62px 22px 22px}.faq-answer p{margin:0;font-size:16px;line-height:1.65}
      .sources-list{margin-top:30px;border-top:1px solid var(--ln)}.source-entry{display:grid;grid-template-columns:220px minmax(0,1fr) auto;gap:26px;align-items:start;padding:24px 0;border-bottom:1px solid var(--ln)}.source-entry strong{display:block;color:var(--tx);font-size:16px;font-weight:600;line-height:1.45}.source-entry small{display:block;margin-top:5px;color:#7A8494;font-size:14px;line-height:1.45}.source-entry p{margin:0;font-size:16px;line-height:1.6}.source-entry .text-link{white-space:nowrap}.conclusion{padding:78px 0;background:var(--sf)}.conclusion-copy{max-width:820px;margin:0 auto;text-align:center}.conclusion-copy p{max-width:760px;margin-left:auto;margin-right:auto;font-size:18px}.related-section{padding:88px 0 94px}.related-heading{display:flex;align-items:end;justify-content:space-between;gap:28px;margin-bottom:32px}.related-heading h2{margin-bottom:0}.related-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 38px;border-top:1px solid var(--ln)}.resource-link{display:block;padding:28px 0;border-bottom:1px solid var(--ln);color:inherit!important}.resource-link h3{margin-bottom:10px;font-size:21px;transition:color .2s}.resource-link p{margin-bottom:14px;font-size:16px;line-height:1.58}.resource-arrow{display:inline-flex;align-items:center;gap:8px;color:var(--m);font-size:15px;font-weight:600}.resource-link:hover h3{color:var(--m)}.final-cta{padding:0 0 112px}.final-box{position:relative;overflow:hidden;padding:64px 56px;border:1px solid #F0D5E1;border-radius:32px;background:radial-gradient(circle at 94% 18%,rgba(193,29,99,.09),transparent 28%),linear-gradient(135deg,var(--bl) 0%,#fff 64%);text-align:center}.final-box h2{max-width:800px;margin-left:auto;margin-right:auto}.final-box>p{max-width:820px;margin-left:auto;margin-right:auto;font-size:18px}.final-box .button-row{justify-content:center}
      @media(max-width:1199px){.shell{padding:0 40px}.article-layout{grid-template-columns:220px minmax(0,1fr);gap:40px}.level{grid-template-columns:64px 200px minmax(0,1fr)}.dark-framework{padding:36px}}
      @media(max-width:900px){.shell{padding:0 28px}.section{padding:82px 0}.pa-guide h1{font-size:42px}.pa-guide h2{font-size:32px}.breadcrumb-wrap{padding-top:22px}.hero{padding:42px 0 70px}.hero-grid{max-width:860px;margin:0 auto}.hero-copy{text-align:center}.hero-copy h1,.hero-copy .lead,.hero-route{margin-left:auto;margin-right:auto}.hero-copy .button-row{justify-content:center}.hero-route{justify-content:center;text-align:left}.takeaways{padding:70px 0}.takeaway-grid{grid-template-columns:1fr;gap:34px}.takeaway-intro{position:static;max-width:760px}.article-region{padding-top:72px}.article-layout{display:block;max-width:820px}.desktop-toc{display:none}.mobile-toc{display:block}.guide-section{max-width:820px;padding-bottom:72px}.three-grid{grid-template-columns:1fr}.scenario{grid-template-columns:1fr;gap:12px}.level{grid-template-columns:58px minmax(0,1fr);gap:16px 20px}.level-copy{grid-column:2}.mid-cta{align-items:flex-start;flex-direction:column}.source-grid,.ai-grid,.trace-grid,.expertise-grid,.checklist-grid{grid-template-columns:1fr}.part{grid-template-columns:1fr;gap:8px}.formal-list,.security-list{grid-template-columns:1fr}.dark-framework{padding:32px}.stage{grid-template-columns:200px minmax(0,1fr)}.risk-route{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.risk-route div{border-right:0;border-bottom:1px solid var(--ln)}.risk-route div:nth-child(odd){border-right:1px solid var(--ln)}.risk-route div:nth-last-child(-n+2){border-bottom:0}.source-entry{grid-template-columns:190px minmax(0,1fr)}.source-entry .text-link{grid-column:2;justify-self:start}}
      @media(max-width:900px){.responsive-table,.responsive-table tbody,.responsive-table tr,.responsive-table td{display:block;width:100%}.responsive-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}.responsive-table tbody{display:grid;gap:14px;padding:14px}.responsive-table tr{padding:16px;border:1px solid var(--ln);border-radius:14px;background:#fff}.responsive-table td{display:grid;grid-template-columns:minmax(132px,.48fr) minmax(0,1fr);gap:14px;padding:9px 0;border:0}.responsive-table td:before{content:attr(data-label);color:#394456;font-size:14px;font-weight:600;line-height:1.45}.responsive-table td:first-child{display:block;padding:0 0 12px;margin-bottom:4px;border-bottom:1px solid var(--ln);font-size:18px}.responsive-table td:first-child:before{display:none}}
      @media(max-width:640px){.shell{padding:0 20px}.section{padding:68px 0}.pa-guide{font-size:17px;line-height:1.7}.pa-guide h1{font-size:38px;line-height:1.22}.pa-guide h2{font-size:30px;line-height:1.22}.pa-guide h3{font-size:21px}.lead{font-size:18px}.breadcrumb-wrap{padding-top:18px}.breadcrumb ol{gap:5px 7px}.hero{padding:32px 0 58px}.hero-copy .button-row{flex-direction:column;align-items:stretch}.btn{width:100%;min-height:52px}.hero-route{display:grid;grid-template-columns:1fr;justify-items:center;gap:8px;margin-top:24px}.hero-route .route-label{margin-bottom:2px}.hero-route .route-arrow{display:none}.takeaways{padding:62px 0}.takeaway-row{grid-template-columns:32px minmax(0,1fr);gap:14px;padding:22px 0}.takeaway-row strong{font-size:18px}.article-region{padding-top:58px}.guide-section{padding-bottom:62px}.mobile-toc{margin-bottom:36px}.chapter-intro{margin-bottom:28px!important;font-size:18px}.scenario{padding:22px;border-radius:18px}.scope-flow,.term-chips{display:grid;grid-template-columns:1fr}.scope-flow span,.term-chips span{justify-content:center;text-align:center}.level{grid-template-columns:44px minmax(0,1fr);padding:24px 0}.level-number{font-size:24px}.level h3{font-size:19px}.mid-cta{padding:22px 0}.mid-cta .btn{width:100%;max-width:100%}.dark-framework{margin-left:-4px;margin-right:-4px;padding:26px 20px;border-radius:22px}.stage{width:100%!important;grid-template-columns:1fr;gap:5px;min-height:0;padding:15px 16px}.risk-route{grid-template-columns:1fr}.risk-route div{border-right:0;border-bottom:1px solid var(--ln)}.risk-route div:last-child{border-bottom:0}.checklist-panel{padding:22px 20px;border-radius:20px}.faq-question{min-height:64px;padding:17px 18px;font-size:16px}.faq-answer{padding:0 18px 20px}.source-entry{grid-template-columns:1fr;gap:10px}.source-entry .text-link{grid-column:1}.conclusion{padding:64px 0}.related-section{padding:68px 0 74px}.related-heading{align-items:flex-start;flex-direction:column}.related-grid{grid-template-columns:1fr}.resource-link{padding:24px 0}.final-cta{padding-bottom:78px}.final-box{padding:46px 22px;border-radius:24px}.final-box .button-row{flex-direction:column}}
      @media(max-width:360px){.pa-guide h1{font-size:36px}.pa-guide h2{font-size:29px}.responsive-table td{grid-template-columns:1fr;gap:4px}}
    `}</style>

    <div className="breadcrumb-wrap"><div className="shell"><nav className="breadcrumb" aria-label="Breadcrumb"><ol>{breadcrumbs.map(b=><li key={b.label}>{b.current?<span className="current" aria-current="page">{b.label}</span>:<a href={b.href}>{b.label}</a>}</li>)}</ol></nav></div></div>

    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Patent Translation Guide</p><h1>Prior Art Translation for Patentability, FTO, and Invalidity</h1><p className="lead">Foreign-language patents and technical publications can become important to patentability research, freedom-to-operate analysis, invalidity investigations, technology landscaping, portfolio due diligence, and competitive intelligence. The key is knowing which documents need translation, which passages matter, and how much linguistic verification is appropriate for the intended use.</p><div className="button-row"><a className="btn btn-primary" href={sectionUrl("research-objectives")} onClick={e=>jump(e,"research-objectives")}>Explore the Guide <Icon name="arrow" size={17}/></a><a className="btn btn-secondary" href={sectionUrl("planning-checklist")} onClick={e=>jump(e,"planning-checklist")}>Jump to the Planning Checklist</a></div><div className="hero-route" aria-label="Guide approach"><span className="route-label">Guide approach</span><span className="route-step">Screen broadly</span><span className="route-arrow" aria-hidden="true">→</span><span className="route-step">Prioritize references</span><span className="route-arrow" aria-hidden="true">→</span><span className="route-step">Translate what matters</span><span className="route-arrow" aria-hidden="true">→</span><span className="route-step">Verify as needed</span></div></div></div></section>

    <section className="takeaways" aria-labelledby="takeaways-heading"><div className="shell takeaway-grid"><div className="takeaway-intro"><p className="eyebrow">Key Takeaways</p><h2 id="takeaways-heading">Five Principles for Translating Foreign-Language Prior Art</h2><p>Use these principles to determine how much translation a patent research project needs and where greater human review can add the most value.</p></div><div className="takeaway-list">{takeaways.map(x=><div className="takeaway-row" key={x.title}><span className="takeaway-mark"><Icon/></span><div><strong>{x.title}</strong><p>{x.text}</p></div></div>)}</div></div></section>

    <section className="article-region"><div className="shell"><div className="article-layout"><aside className="desktop-toc"><nav aria-label="Guide sections"><p className="toc-title">In This Guide</p><ul className="toc-list">{tocItems.map(x=><li key={x.id}><a className={`toc-link ${activeId===x.id?"active":""}`} href={sectionUrl(x.id)} aria-current={activeId===x.id?"location":undefined} onClick={e=>jump(e,x.id)}>{x.label}</a></li>)}</ul></nav></aside><div className="article-main"><details className="mobile-toc"><summary>In This Guide</summary><nav aria-label="Guide sections"><ul className="toc-list">{tocItems.map(x=><li key={x.id}><a className={`toc-link ${activeId===x.id?"active":""}`} href={sectionUrl(x.id)} aria-current={activeId===x.id?"location":undefined} onClick={e=>jump(e,x.id)}>{x.label}</a></li>)}</ul></nav></details>

      <section className="guide-section" id="research-objectives" aria-labelledby="research-objectives-heading"><div className="reading"><h2 id="research-objectives-heading">One Foreign Patent Can Matter for Very Different Reasons</h2><p className="chapter-intro">A foreign-language patent document does not have one universal research purpose. The same publication may be reviewed during a patentability search, considered during an FTO investigation, examined as potential invalidity material, or used to understand a competitor or technology landscape. The translation strategy should change accordingly.</p></div><div className="three-grid"><article className="question"><h3><span>01</span>Patentability</h3><p>Patentability research considers whether earlier information may be relevant to requirements such as novelty and inventive step or non-obviousness under the applicable patent system. Translation may need to reveal technical disclosure, embodiments, examples, relevant claims, and where particular features appear.</p></article><article className="question"><h3><span>02</span>Freedom to Operate</h3><p>FTO research asks whether patent rights that may still be enforceable in a particular country or region could be relevant to a proposed product, process, or commercial activity. Claims, patent-family context, jurisdiction, and legal-status information can therefore become especially important.</p></article><article className="question"><h3><span>03</span>Invalidity</h3><p>Invalidity research may examine earlier patents, printed publications, technical literature, or other potentially relevant material under the law and procedure applicable to the matter. Translation depth often increases as the research narrows.</p></article></div><div className="important-note"><strong>Important Distinction</strong><p>An FTO-relevant patent is not necessarily prior art against the client’s own patent. It may matter because of potentially enforceable third-party rights rather than because it predates or affects patentability of another invention.</p></div><div className="source-note"><strong>Official guidance:</strong><span>WIPO describes FTO searches as country- or region-specific and focused on potentially relevant patent rights, claims, and legal status. <a href="https://www.wipo.int/en/web/patentscope/db/glossary" target="_blank" rel="noreferrer">Review WIPO guidance ↗</a></span></div><div className="legal-boundary"><strong>Translation Support, Not Legal Advice</strong><p>Stepes provides linguistic, technical, and multilingual workflow support. We do not determine patentability, infringement, freedom to operate, claim scope, validity, invalidity, prior-art status, critical dates, or other legal conclusions. Those determinations remain with the client and its qualified patent professionals.</p></div></section>

      <section className="guide-section" id="translation-depth" aria-labelledby="translation-depth-heading"><div className="reading"><h2 id="translation-depth-heading">Translate According to the Decision, Not Just the Document</h2><p className="chapter-intro">The source document may be the same while the appropriate translation scope changes dramatically with the research question.</p><div className="scenario"><div><span className="scenario-label">Illustrative Scenario</span></div><div><p>A patent search identifies a 70-page Japanese patent publication. One team may initially need only the abstract and front-page information for a landscape study. Another may want independent claims translated for preliminary FTO review. A patentability researcher may identify several embodiments for professional translation. If the document later becomes important to litigation or another formal proceeding, the entire publication may require a carefully reviewed translation.</p><div className="scope-flow"><span>Abstract screening</span><span>Claims</span><span>Selected embodiments</span><span>Complete translation</span><span>Verified delivery</span></div></div></div><p style={{marginTop:26}}>A staged approach helps organizations allocate professional translation effort where it provides the greatest value while still giving researchers timely access to large volumes of foreign-language information.</p></div></section>

      <section className="guide-section" id="translation-levels" aria-labelledby="translation-levels-heading"><div className="reading"><h2 id="translation-levels-heading">Five Levels of Translation for Patent Research</h2><p className="chapter-intro">Prior art translation can range from rapid research comprehension to fully reviewed translations prepared for formal use. Defining the intended level at the beginning helps align cost, turnaround, linguist expertise, quality controls, and delivery format.</p></div><div className="levels">{levels.map(x=><article className="level" key={x.number}><span className="level-number">{x.number}</span><h3>{x.title}</h3><div className="level-copy"><p>{x.text}</p><span className="level-use"><strong>Typical fit:</strong> {x.uses}</span></div></article>)}</div><div id="decision-matrix" style={{scrollMarginTop:112}}><div className="matrix-heading"><h3>How Much Translation Does the Research Require?</h3><p>A useful planning model is to begin with the minimum level needed for informed review and escalate the documents that become important.</p></div><div className="table-wrap"><table className="responsive-table"><thead><tr><th scope="col">Research Objective</th><th scope="col">Typical Starting Point</th><th scope="col">Content Often Prioritized</th><th scope="col">Escalate When</th><th scope="col">Possible Final Level</th></tr></thead><tbody>{decisionRows.map(x=><tr key={x.objective}><td data-label="Research Objective">{x.objective}</td><td data-label="Typical Starting Point">{x.start}</td><td data-label="Content Often Prioritized">{x.prioritize}</td><td data-label="Escalate When">{x.escalate}</td><td data-label="Possible Final Level">{x.final}</td></tr>)}</tbody></table></div><p className="matrix-note">The project team directing the patent research should determine the legal and analytical significance of each reference. Stepes can then align translation depth, review level, technical expertise, workflow, and delivery format with those instructions.</p><div className="mid-cta"><strong>Need to plan a staged workflow across a multilingual patent research set?</strong><a className="btn btn-secondary" href={links.contact}>Discuss a Prior Art Translation Project</a></div></div></section>

      <section className="guide-section" id="patentability" aria-labelledby="patentability-heading"><div className="reading"><h2 id="patentability-heading">Translation for Patentability and Prior Art Research</h2><p className="chapter-intro">Patentability research can cross borders quickly. Important technical disclosures may appear in patent publications, academic literature, standards, conference materials, product documentation, or other sources published in languages unfamiliar to the research team.</p><div className="subsection"><h3>Understand What the Reference Actually Discloses</h3><p>Depending on the research instructions, reviewers may need access to technical concepts, claimed features, embodiments, process sequences, component relationships, materials, formulations, experimental data, figures, definitions, terminology, cited references, and bibliographic information.</p><p>The translation provider’s role is to reproduce the relevant technical meaning accurately. Patent professionals determine whether and how that disclosure affects patentability.</p></div><div className="subsection"><h3>Abstracts Are Valuable for Screening, but Not Always Enough</h3><p>Patent abstracts are extremely useful for search-result screening, but they do not reproduce every limitation, embodiment, condition, example, definition, or technical relationship contained in a complete patent document.</p><p>When an abstract indicates that a reference could be important, the next step may be translation of selected claims or specification passages rather than an immediate full-document translation.</p></div><div className="subsection"><h3>Escalate When the Reference Becomes Important</h3><p>A common workflow can move from abstract or machine-assisted screening to a researcher shortlist, selected professional translation, and complete translation for priority references.</p></div><ExternalLink href="https://www.epo.org/en/legal/guidelines-epc/2026/g_vii_1.html">Review EPO Guidance on Novelty and Inventive Step</ExternalLink><p style={{marginTop:16}}><a className="text-link" href={links.patentServices}><span>Explore Patent Translation Services</span><Icon name="arrow" size={16}/></a></p></div></section>

      <section className="guide-section" id="fto" aria-labelledby="fto-heading"><div className="reading"><h2 id="fto-heading">Translation Support for Freedom-to-Operate Research</h2><p className="chapter-intro">FTO analysis requires careful distinction from general prior-art research. A patent may be highly relevant to an FTO investigation even if it would not function as prior art against another patent.</p><div className="subsection"><h3>Why Claims Deserve Additional Attention</h3><p>Patent claims can contain independent and dependent relationships, technical limitations, defined terms, alternative elements, antecedent references, numerical ranges, process steps, component relationships, and nested dependencies.</p><p>Small linguistic differences can materially change how a reader understands the text. Claim translation should preserve source structure and terminology closely enough for qualified patent professionals to perform their own analysis. Stepes translates claim language; we do not interpret or determine legal claim scope.</p><a className="text-link" href={links.claimsChecklist}><span>Patent Claims Translation Quality Checklist</span><Icon name="arrow" size={16}/></a></div><div className="subsection"><h3>Patent Family and Jurisdiction Context</h3><p>FTO investigations are territorial. A patent family may include applications or grants in multiple jurisdictions, and those family members may differ in claim language, status, or prosecution history.</p><p>Translation projects should identify the specific documents and jurisdictions selected for review rather than assuming one family member represents every related right.</p></div><div className="subsection"><h3>Claims May Not Be the Entire Translation Scope</h3><p>Reviewers may also request portions of the description, definitions, embodiments, figures, prosecution materials, or related family documents for additional technical context. The appropriate scope should be specified by counsel or the research team.</p></div><ExternalLink href="https://www.wipo.int/tisc/en/docs/tisc-toolkit-freedom-to-operate-description.pdf">Review WIPO Freedom-to-Operate Guidance</ExternalLink></div></section>

      <section className="guide-section" id="invalidity" aria-labelledby="invalidity-heading"><div className="reading"><h2 id="invalidity-heading">Translation for Invalidity and Validity Research</h2><p className="chapter-intro">Invalidity research can involve an especially large difference between the number of documents initially identified and the number that ultimately become important. That makes staged translation particularly useful.</p><div className="subsection"><h3>Start Broad</h3><p>Early search results can be screened using abstracts, machine-assisted translation, bibliographic data, keywords, classifications, or high-level document comprehension. The objective is to help researchers determine which foreign-language references merit additional investigation.</p></div><div className="subsection"><h3>Narrow to Specific Disclosures</h3><p>Researchers or counsel may identify claims, numbered paragraphs, feature descriptions, examples, experimental results, tables, drawings, definitions, relevant citations, or other targeted passages for professional translation.</p></div><div className="subsection"><h3>Escalate Strong References</h3><p>When a document becomes important to an invalidity position, expert opinion, litigation strategy, post-grant proceeding, negotiation, or other major decision, the translation workflow can escalate to full professional translation, independent linguistic review, and a final bilingual or certified deliverable when requested.</p></div><div className="subsection"><h3>Formal Proceedings Require Matter-Specific Instructions</h3><p>Translation requirements can vary by court, tribunal, patent office, administrative procedure, jurisdiction, and matter. Counsel should determine the scope, evidentiary requirements, legal significance, and appropriate use of the translation.</p></div><ExternalLink href="https://www.uspto.gov/patents/ptab/trials/inter-partes-review">Review USPTO Inter Partes Review Information</ExternalLink></div></section>

      <section className="guide-section" id="prior-art-sources" aria-labelledby="prior-art-sources-heading"><div className="reading"><h2 id="prior-art-sources-heading">Foreign-Language Prior Art Is Not Limited to Patents</h2><p className="chapter-intro">Patent databases are an essential source of technical information, but patent research can extend beyond patent literature. Potentially relevant materials may appear in many forms and languages.</p></div><div className="source-grid"><div className="source-group"><h3>Patent Literature</h3><ul>{["Published patent applications","Granted patents","Utility models","Patent family members","International patent publications","Search and examination reports","Cited patent references","Patent abstracts","Published prosecution-related material where applicable"].map(x=><li key={x}>{x}</li>)}</ul></div><div className="source-group"><h3>Scientific, Technical, and Industry Information</h3><ul>{["Journal articles and research papers","Conference proceedings","Academic theses and technical books","Scientific reports","Technical standards","Product manuals and datasheets","Catalogs and white papers","Engineering documentation","Archived technical webpages or publications"].map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="important-note"><strong>Legal Significance Depends on the Matter</strong><p>The fact that a document exists or was published does not by itself establish its legal status as prior art in a particular matter. Relevant dates, public accessibility, governing law, evidentiary issues, and other circumstances may matter. Stepes translates the material identified for research; patent professionals determine its legal significance.</p></div><div className="source-note"><strong>Official guidance:</strong><span>USPTO guidance on printed publications emphasizes public accessibility rather than simply whether something was physically printed. <a href="https://www.uspto.gov/web/offices/pac/mpep/s2128.html" target="_blank" rel="noreferrer">Review MPEP § 2128 ↗</a></span></div></section>

      <section className="guide-section" id="document-parts" aria-labelledby="document-parts-heading"><div className="reading"><h2 id="document-parts-heading">Claims, Specifications, Figures, and Examples Serve Different Purposes</h2><p className="chapter-intro">A prior-art translation project does not necessarily begin or end with complete document translation. Different parts of the document can provide different information to the research team.</p></div><div className="part-list">{[
        ["Patent Claims","Claims require attention to structure, dependencies, technical limitations, defined terms, repeated terminology, numbers, units, alternatives, and relationships among elements. Claims can be especially important in FTO and other claim-focused research."],
        ["Detailed Description and Embodiments","The detailed description can reveal technical information that does not appear in an abstract or may not be fully expressed in the claims, including how a system operates, how elements interact, or how an invention was implemented."],
        ["Examples and Experimental Data","Examples can be especially important in pharmaceuticals, biotechnology, chemistry, materials science, medical technologies, and manufacturing processes. Translation may need to preserve substances, concentrations, temperatures, ranges, units, test methods, observations, and results."],
        ["Figures, Drawings, and Tables","Drawings can contain labels, legends, reference numerals, flowchart text, graph labels, callouts, or other language-dependent information. Tables may contain experimental data, formulations, measurements, classifications, or technical comparisons."],
        ["Bibliographic Information and Citations","Patent numbers, publication numbers, application numbers, inventor names, assignees, cited literature, and other identifiers should remain traceable to the source without the translation team determining which dates or legal relationships control the analysis."],
        ["Non-Patent Literature","Scientific papers, standards, manuals, theses, and other technical documents follow different structures from patents, but the underlying translation requirements remain similar: technical accuracy, clear scope, terminology consistency, and source traceability."],
      ].map(([t,p])=><article className="part" key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></section>

      <section className="guide-section" id="progressive-workflow" aria-labelledby="workflow-heading"><div className="dark-framework dark"><p className="eyebrow">Translation Routing Framework</p><h2 id="workflow-heading">From Hundreds of Search Results to a Handful of Critical References</h2><p className="framework-intro">Large multilingual patent searches can make complete human translation of every result impractical and unnecessary. A progressive workflow uses the fastest appropriate comprehension method across the broadest part of the research set, then increases professional translation and linguistic control as the number of documents decreases and their importance rises.</p><div className="funnel" aria-label="Illustrative progressive translation workflow">{[
        ["100+ Search References","Bibliographic, abstract, or AI-assisted screening","100%"],
        ["Potentially Relevant Set","Technical summaries and targeted human review","88%"],
        ["20 Priority References","Selected claims, paragraphs, embodiments, or examples","76%"],
        ["5 High-Priority References","Complete professional translation","64%"],
        ["1–2 Decision-Critical Documents","Independent verification or matter-specific preparation","52%"],
      ].map(([a,b,w])=><div className="stage" key={a} style={{width:w}}><strong>{a}</strong><span>{b}</span></div>)}</div><p className="framework-note">Illustrative workflow only. Actual research volumes and translation requirements vary significantly by project.</p></div></section>

      <section className="guide-section" id="ai-screening" aria-labelledby="ai-screening-heading"><div className="reading"><h2 id="ai-screening-heading">Use AI to Accelerate Research, Then Increase Human Control With Risk</h2><p className="chapter-intro">AI and machine translation have changed how quickly large collections of multilingual patent information can be understood at a high level. The strongest workflow does not require choosing between AI and humans; it uses each where it provides the most value.</p></div><div className="ai-grid"><div className="ai-col"><h3><Icon name="search" size={20}/>AI-Assisted Uses</h3><ul>{["Large-volume document screening","Initial research comprehension","Patent abstract review","Technical terminology extraction","Patent-family and version comparison","Identifying passages for further review","Multilingual search-result triage","Automated linguistic QA assistance"].map(x=><li key={x}>{x}</li>)}</ul></div><div className="ai-col"><h3><Icon name="target" size={20}/>Human-Centered Uses</h3><ul>{["Decision-critical claims","Complex or ambiguous technical disclosures","Selected passages on which an analysis depends","Complete translations of high-priority references","Expert-review materials","Formal proceedings","Certified or independently verified translations"].map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="risk-route"><div><strong>Broad Search</strong><span>AI-assisted comprehension</span></div><div><strong>Priority Set</strong><span>Targeted human review</span></div><div><strong>High-Priority References</strong><span>Professional translation</span></div><div><strong>Decision-Critical Use</strong><span>Independent verification as needed</span></div></div><div className="important-note"><strong>What AI Should Not Decide</strong><p>AI can help answer, “What does this document appear to be about, and should a qualified reviewer look more closely?” It should not be presented as independently deciding anticipation, obviousness, infringement, freedom to operate, validity, or invalidity.</p></div><div className="source-note"><strong>Current practice:</strong><span>EPO PCT guidance recognizes machine translation as a way to overcome language barriers in prior-art review while also allowing a better translation to be provided when meaning is disputed. <a href="https://www.epo.org/en/legal/guidelines-pct/2026/g_iv_4_1.html" target="_blank" rel="noreferrer">Review the EPO guidance ↗</a></span></div><p style={{marginTop:22}}><a className="text-link" href={links.aiPatentGuide}><span>AI Patent Translation: Research Use vs. Filing-Grade Translation</span><Icon name="arrow" size={16}/></a></p></section>

      <section className="guide-section" id="traceability" aria-labelledby="traceability-heading"><div className="reading"><h2 id="traceability-heading">Keep Every Translation Connected to the Original Reference</h2><p className="chapter-intro">For patent research, fluent target-language prose is not enough. Attorneys, search professionals, engineers, experts, and investigators may need to return repeatedly to the original document to verify context and compare passages.</p></div><div className="trace-grid">{[
        ["Preserve Source References","Publication numbers, application numbers, claims, paragraphs, page references, section headings, figures, tables, equations, footnotes, and literature citations should remain easy to locate."],
        ["Bilingual Review Formats","Source and translated content can be presented together when side-by-side review helps attorneys, technical experts, and bilingual reviewers move efficiently between languages."],
        ["Clearly Identify Partial Scope","Selected-passage translation should clearly identify the claims, paragraphs, pages, figures, tables, or sections included so readers do not mistake partial coverage for a complete translation."],
        ["Keep Research Context Intact","Source identifiers and formatting should support discussion among counsel, researchers, engineers, and experts without obscuring where translated information came from."],
      ].map(([a,b])=><div className="trace-item" key={a}><strong>{a}</strong><p>{b}</p></div>)}</div></section>

      <section className="guide-section" id="terminology" aria-labelledby="terminology-heading"><div className="reading"><h2 id="terminology-heading">One Technical Vocabulary Across Related References</h2><p className="chapter-intro">Patent research often involves related families, multiple inventors, several languages, and numerous publications describing similar technologies. A controlled terminology framework can help reviewers compare documents without introducing unnecessary variation through translation.</p><div className="term-chips">{["Related patent-family members","Approved translations","Client glossaries","Product terminology","Scientific nomenclature","Technical standards","Translation memories","Earlier research translations","Attorney or expert feedback"].map(x=><span key={x}>{x}</span>)}</div><p style={{marginTop:24}}>Terminology should still be interpreted in the context of each actual source. Wording used in one patent should not be copied mechanically into another when technical meaning or claim context changes.</p><a className="text-link" href={links.terminology}><span>Explore Terminology Management</span><Icon name="arrow" size={16}/></a></div></section>

      <section className="guide-section" id="technical-expertise" aria-labelledby="expertise-heading"><div className="reading"><h2 id="expertise-heading">Translate the Technology, Not Just the Words</h2><p className="chapter-intro">Prior-art research can reach highly specialized areas of science and engineering. Accurate translation therefore depends on both language capability and subject-matter understanding.</p></div><div className="expertise-grid">{expertise.map(x=><article className="expertise-item" key={x.title}><h3>{x.title}</h3><p>{x.text}</p>{x.href&&<a className="text-link" href={x.href}><span>{x.linkLabel}</span><Icon name="arrow" size={16}/></a>}</article>)}</div></section>

      <section className="guide-section" id="quality-control" aria-labelledby="quality-heading"><div className="reading"><h2 id="quality-heading">What Should Be Checked Before a Translation Supports a Major IP Decision?</h2><p className="chapter-intro">A decision-critical prior-art translation should be reviewed systematically rather than judged only by whether the target language reads naturally.</p></div><div className="table-wrap"><table className="responsive-table"><thead><tr><th scope="col" style={{width:"26%"}}>Quality Area</th><th scope="col">What to Verify</th></tr></thead><tbody>{qualityRows.map(x=><tr key={x.area}><td data-label="Quality Area">{x.area}</td><td data-label="What to Verify">{x.check}</td></tr>)}</tbody></table></div><p style={{marginTop:22}}>For decision-critical references, quality should be evaluated together with source traceability, translation scope, terminology consistency, and the review level appropriate to the intended use.</p><p style={{marginTop:16}}><a className="text-link" href={links.claimsChecklist}><span>Review the Patent Claims Translation Quality Checklist</span><Icon name="arrow" size={16}/></a></p></section>

      <section className="guide-section" id="formal-use" aria-labelledby="formal-use-heading"><div className="reading"><h2 id="formal-use-heading">From Research Translation to Formal Use</h2><p className="chapter-intro">Most documents screened during patent research do not need certified translation. The required level can change when a reference moves from internal research into a formal proceeding, expert analysis, administrative review, litigation matter, or another documented use.</p><ul className="formal-list">{["Complete professional human translation","Independent linguistic review","Technical review","Signed translator certification","Translator declarations","Bilingual exhibits","Special formatting","Document identification requirements"].map(x=><li key={x}>{x}</li>)}</ul><p style={{marginTop:24}}>Certification does not determine legal admissibility or evidentiary weight. Acceptance requirements should be confirmed by the client’s counsel and the applicable court, patent office, administrative body, or other receiving authority.</p><a className="text-link" href={links.certified}><span>Explore Certified Translation Services</span><Icon name="arrow" size={16}/></a></div></section>

      <section className="guide-section" id="confidentiality" aria-labelledby="confidentiality-heading"><div className="reading"><h2 id="confidentiality-heading">Protect Unpublished Inventions and Sensitive Research</h2><p className="chapter-intro">Patent research can involve information far beyond published prior art. Translation and AI usage should reflect the confidentiality requirements of the specific matter.</p><ul className="security-list">{["Unpublished inventions","Future products and product roadmaps","R&D strategies and technical designs","Potential patent challenges","Litigation strategy","Acquisition targets","Licensing positions","Confidential search results"].map(x=><li key={x}>{x}</li>)}</ul><p style={{marginTop:24}}>Before sensitive material is processed, organizations should consider what information will be translated, who needs access, whether AI-assisted processing is permitted, how reference materials should be handled, and what project-specific security instructions apply.</p><p>Stepes can align multilingual translation workflows with the confidentiality and access requirements supplied for the project.</p></div></section>

      <section className="guide-section" id="planning-checklist" aria-labelledby="planning-checklist-heading"><div className="reading"><h2 id="planning-checklist-heading">Before You Send Prior Art for Translation</h2><p className="chapter-intro">Good project instructions can improve speed, consistency, and translation quality while reducing unnecessary work. Use this checklist when preparing foreign-language patent or technical references for translation.</p></div><div className="checklist-panel"><div className="checklist-grid">{checklistGroups.map(g=><section className="check-group" key={g.title}><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><span className="checkmark" aria-hidden="true"/><span>{x}</span></li>)}</ul></section>)}</div></div></section>

      <section className="guide-section" id="faqs" aria-labelledby="faqs-heading"><div className="reading"><h2 id="faqs-heading">Frequently Asked Questions About Prior Art Translation</h2><p className="chapter-intro">Practical answers to common questions about translation scope, AI-assisted screening, claims, certification, and multilingual research.</p></div><div className="faq-wrap">{faqs.map((x,i)=>{const open=openFaq===i,id=`prior-art-faq-answer-${i}`;return <div className="faq-item" key={x.q}><button type="button" className="faq-question" aria-expanded={open} aria-controls={id} onClick={()=>setOpenFaq(open?null:i)}><span>{x.q}</span><span className="faq-symbol" aria-hidden="true">{open?"–":"+"}</span></button><div id={id} className="faq-answer" hidden={!open}><p>{x.a}</p></div></div>})}</div></section>

      <section className="guide-section" id="official-sources" aria-labelledby="sources-heading"><div className="reading"><h2 id="sources-heading">Authoritative Patent Research Resources</h2><p className="chapter-intro">Current official patent-office and international sources should be used when determining patent law, procedure, search methodology, legal status, or filing requirements. Stepes provides translation support; qualified patent professionals remain responsible for legal conclusions.</p></div><div className="sources-list">{sources.map(s=><div className="source-entry" key={s.title}><div><strong>{s.title}</strong><small>{s.organization}</small></div><p>{s.text}</p><ExternalLink href={s.href}>Visit Source</ExternalLink></div>)}</div></section>

    </div></div></div></section>

    <section className="conclusion"><div className="shell"><div className="conclusion-copy"><h2>Match Translation Effort to Research Importance</h2><p>Not every foreign-language reference requires the same level of translation. Start with the research question, screen broadly, narrow progressively, and increase professional translation and human verification as a reference becomes more important to the decision.</p></div></div></section>

    <section className="related-section" id="related-resources" aria-labelledby="related-heading"><div className="shell"><div className="related-heading"><div><h2 id="related-heading">Continue Your Patent Translation Research</h2></div><a className="text-link" href={links.translationGuides}><span>Browse Translation Guides</span><Icon name="arrow" size={16}/></a></div><div className="related-grid">{related.map(r=><a className="resource-link" href={r.href} key={r.title}><h3>{r.title}</h3><p>{r.text}</p><span className="resource-arrow">Explore Resource <Icon name="arrow" size={16}/></span></a>)}</div></div></section>

    <section className="final-cta" id="final-cta"><div className="shell"><div className="final-box"><h2>Turn Foreign-Language Patent Research Into Actionable Information</h2><p>Whether your research project involves hundreds of documents requiring rapid screening, a shortlist needing selected-passage translation, or one decision-critical reference requiring comprehensive professional review, Stepes can align the multilingual workflow with your team’s research instructions.</p><div className="button-row"><a className="btn btn-primary" href={links.contact}>Discuss a Prior Art Translation Project <Icon name="arrow" size={17}/></a><a className="btn btn-secondary" href={links.quote}>Get a Quote</a></div></div></div></section>
  </main>;
}
